apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-zone-csi
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_ZRS  # available values: Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS, Premium_ZRS, StandardSSD_ZRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
# allowedTopologies:
# - matchLabelExpressions:
#   - key: topology.kubernetes.io/zone
#     values:
#     - westus2-1
#     - westus2-2
