apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-zrs-csi-premium
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_ZRS  # available values: Standard_LRS, Premium_LRS, StandardSSD_LRS, PremiumV2_LRS, UltraSSD_LRS, Premium_ZRS, StandardSSD_ZRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
# allowedTopologies:
# - matchLabelExpressions:
#   - key: topology.kubernetes.io/zone
#     values:
#     - australiaeast-1
#     - australiaeast-2
