---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zrs-azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-zrs-csi-premium
