---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zone-azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-zone-csi