---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stateful-app  
  template:
    metadata:
      labels:
        name: stateful-app
    spec:
      containers:
        - image: mcr.microsoft.com/cbl-mariner/base/core:2.0
          name: mariner-azuredisk
          command:
            - "/bin/sh"
            - "-c"
            - while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 1; done
          volumeMounts:
            - name: azuredisk01
              mountPath: "/mnt/azuredisk"
          livenessProbe:
            exec:
              command:
              - /bin/ls
              - /mnt/azuredisk/outfile
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - /bin/ls
              - /mnt/azuredisk/outfile
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 2
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
      # See: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/docs/known-issues/node-shutdown-recovery
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      terminationGracePeriodSeconds: 10
      volumes:
        - name: azuredisk01
          persistentVolumeClaim:
            claimName: pvc-zrs-azuredisk
